# DSN (Database Source Name) to connect database
dsn: ${DATABASE_URL}?sslmode=disable

# Path to generate document
docPath: doc/db
dict:
  Tables: テーブル一覧
  Description: 概要
  Columns: カラム一覧
  Indexes: INDEX一覧
  Constraints: 制約一覧
  Triggers: トリガー
  Relations: ER図
  Name: 名前
  Comment: コメント
  Type: タイプ
  Default: デフォルト値
  Children: 子テーブル
  Parents: 親テーブル
  Definition: 定義
  Table Definition: テーブル定義
  Viewpoints: 集約
lint:
  requireColumnComment:
    enabled: true
    exclude:
      - id
      - createdAt
      - updatedAt
  requireTableComment:
    enabled: true

lintExclude:
  - _prisma_migrations
  - graphile_worker.migrations
  - graphile_worker.job_queues
  - graphile_worker.jobs
  - graphile_worker.known_crontabs
