services:
  db:
    restart: always
    image: postgres:11
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    ports:
      - 5000:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
volumes:
  db-data:
